### ISSUE TITLE
Cannot push because of unlink error exception

### ISSUE THREAD

**Issue by ayoubeddafali** [Elendev/nexus-composer-push#37] opened 2020-11-03 11:58 UTC
Hello There, 

I am unable to push artefacts to Nexus, when running **composer nexus-push 1.0.0 -vvv**
The error logs has the following messages ( with verbose mode ) : 

```
Reading ./composer.json
Loading config file ./composer.json
Loading config file /home/user/Desktop/random-password/auth.json
Reading /home/user/Desktop/random-password/auth.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Failed to initialize global composer: Composer could not find the config file: /home/user/.config/composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/user/Desktop/random-password/vendor/composer/installed.json
Loading plugin Elendev\NexusComposerPush\Plugin
Running 2.0.4 (2020-10-30 22:39:11) with PHP 7.4.12 on Linux / 5.4.0-52-generic
Ignore directories: .gitattributes .gitignore phpunit.xml  README.md vendor/
Execute the Nexus Push for the URL https://localhost:8081/repository/composer-test-1/packages/upload/mazraara/random-password/1.0.0...
[postFile] Trying credentials auth.json
Remove file /tmp/nexus-pushJ3zfJM.zip

                                                                
  [ErrorException]                                              
  unlink(/tmp/nexus-pushJ3zfJM.zip): No such file or directory  
...
...

 [ErrorException]                                                                    
  fopen(/tmp/nexus-pushJ3zfJM.zip): failed to open stream: No such file or directory  
                                                                

```

When I check the /tmp folder I only see the name without the extension : 
-rw-------  1 user user       0 Nov  3 12:55  nexus-pushJ3zfJM

so probably there is some issue when Zipping the actual directory. 

Note: I can still push using curl cmdline.

**Comment by Elendev** [comment] 2020-11-03 15:41
Hello @ayoubeddafali, I have some questions to help me diagnose what the issue is:
 - Which version of the plugin are you using?
 - Is `nexus-pushJ3zfJM` an empty zip file?

Thanks in advance!

**Comment by ayoubeddafali** [comment] 2020-11-03 15:59
Hello @Elendev , 

Thanks for the response. 

- It seems that I am using **9999999-dev**, after running the composer require. 

- `nexus-pushJ3zfJM` is not actually a zip file, it's an empty file with no extension. 

Thanks again

**Comment by Elendev** [comment] 2021-07-15 12:54
Hello @ayoubeddafali, sorry I didn't answered this issue sooner. There has been a lot of updates since the time you had this issue, do you still encounter it with the latest version?
I'll close this issue, don't hesitate to re-open it if you still encounter the same issue.
Cheers

**Closed by Elendev** 2021-07-15 12:54 UTC
